// Code generated by protoc-gen-go-cli. DO NOT EDIT.
// versions:
// 	protoc        (unknown)
package main

import (
	cobra "github.com/spf13/cobra"
	v1 "github.com/ycj-ymatrix/stream-service/gen/api/v1"
	cli "go.einride.tech/protoc-gen-go-cli/cli"
)

func NewRootCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use: "stream-cli",
	}
	cmd.AddCommand(v1.NewStreamDemoServiceCommand("stream-demo"))
	return cmd
}

func NewConfig() *cli.Config {
	return &cli.Config{
		Compiler: cli.CompilerConfig{Hosts: map[string]string{}, DefaultHost: "", Root: "stream-cli", GoogleCloudIdentityTokens: false, Main: true},
	}
}
